<h1>Peer-graded Assignment: <br>Segmenting and Clustering Neighborhoods in Toronto</h1>
<h3>Assignment to test Pandas knowledge as well as Geolocation and Mapping.<br> 
    This data will be used to cluster similar neighborhoods in Toronto by employing <br>
    K-means Clustering and Scikit-learn</h3>

<h4>***Import necessary modules for data cleaning and manipulation -- in this case Pandas***</h4>

In [2]:
import pandas as pd

<h4>Using data from Wikipedia I will import the table into Pandas, format it, and ,view to see if loaded correctly<h4>

In [3]:
url = r'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [4]:
table_toronto = pd.read_html(url)
table_toronto = table_toronto[0]
table_toronto.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

<h4>I will now first remove any rows where the Borough is not assigned and reset index</h4>

In [5]:
pd_borough= table_toronto.loc[table_toronto['Borough'] != 'Not assigned',].reset_index()
pd_borough = pd_borough[['Postcode', 'Borough','Neighbourhood']]
pd_borough.head()

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights

<h4>I am creating a pandas groupby object to stack postal codes for easier manipulation later</h4>

In [6]:
df_by_pc = pd_borough.groupby('Postcode')
df_by_pc.head(5)

,Postcode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,Harbourfront
3,M5A,Downtown Toronto,Regent Park
4,M6A,North York,Lawrence Heights
5,M6A,North York,Lawrence Manor
6,M7A,Queen's Park,Not assigned
7,M9A,Etobicoke,Islington Avenue
8,M1B,Scarborough,Rouge
9,M1B,Scarborough,Malvern
10,M3B,North York,Don Mills North
11,M4B,East York,Woodbine Gardens
12,M4B,East York,Parkview Hill
13,M5B,Downtown Toronto,Ryerson
14,M5B,Downtown Toronto,Garden District
15,M6B,North York,Glencairn
16,M9B,Etobicoke,Cloverdale
17,M9B,Etobicoke,Islington
18,M9B,Etobicoke,Martin Grove
19,M9B,Etobicoke,Princess Gardens
20,M9B,Etobicoke,West Deane Park
21,M1C,Scarborough,Highland Creek
22,M1C,Scarborough,Rouge Hill
23,M1C,Scarborough,Port Union
24,M3C,North York,Flemingdon Park
25,M3C,North York,Don Mills South
26,M4C,East York,Woodbine Heights
27,M5C,Downtown Toronto,St. James Town
28,M6C,York,Humewood-Cedarvale
29,M9C,Etobicoke,Bloordale Gardens
...,...,...,...
175,M9V,Etobicoke,Beaumond Heights
176,M9V,Etobicoke,Humbergate
177,M9V,Etobicoke,Jamestown
178,M9V,Etobicoke,Mount Olive
182,M1W,Scarborough,L'Amoreaux West
183,M4W,Downtown Toronto,Rosedale
184,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade
185,M8W,Etobicoke,Alderwood
186,M8W,Etobicoke,Long Branch
187,M9W,Etobicoke,Northwest
188,M1X,Scarborough,Upper Rouge
189,M4X,Downtown Toronto,Cabbagetown
190,M4X,Downtown Toronto,St. James Town
191,M5X,Downtown Toronto,First Canadian Place
192,M5X,Downtown Toronto,Underground city
193,M8X,Etobicoke,The Kingsway
194,M8X,Etobicoke,Montgomery Road
195,M8X,Etobicoke,Old Mill North
196,M4Y,Downtown Toronto,Church and Wellesley
197,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
198,M8Y,Etobicoke,Humber Bay
199,M8Y,Etobicoke,King's Mill Park
200,M8Y,Etobicoke,Kingsway Park South East
201,M8Y,Etobicoke,Mimico NE
202,M8Y,Etobicoke,Old Mill South
206,M8Z,Etobicoke,Kingsway Park South West
207,M8Z,Etobicoke,Mimico NW
208,M8Z,Etobicoke,The Queensway West
209,M8Z,Etobicoke,Royal York South West
210,M8Z,Etobicoke,South of Bloor

<h4>Below I am creating an empty data freame for later use</h4>

In [7]:
nb_df_combine = pd.DataFrame(columns = list(pd_borough.columns))
nb_df_combine

Empty DataFrame
Columns: [Postcode, Borough, Neighbourhood]
Index: []

<h4>     Here I iterate through a list of unique postal codes and append the neighborhoods in each 
     to a list. I then append this list to the newly empty <br> <br>datarame created earlier along with 
     the correct Postal code and Borough name. I made the assumption that specific Boroughs were 
    in Specific Postal <br><br> codes and verified by viewing the data</h4>

In [8]:
temp_list = []
#find number of unique postcodes from grouby dataset. I use list to access information from the groupby object
for i in range(len(df_by_pc['Postcode'].unique())):
    for nbh in list(df_by_pc)[i][1]['Neighbourhood']:
         temp_list.append(nbh) 
    #combine list of neighborhoods into a comma seperated string        
    temp_list_1 = ', '.join(str(e) for e in temp_list)
    #Create row for appending to the dataset
    data = {'Neighbourhood': temp_list_1,
            'Postcode':(list(df_by_pc)[i][1]['Postcode'].unique())[0],
           'Borough': pd_borough[pd_borough['Postcode']== (list(df_by_pc)[i][1]['Postcode'].
                                                           unique())[0]]['Borough'].unique()[0]}
    nb_df_combine = nb_df_combine.append(data, ignore_index=True)
    temp_list = []
nb_df_combine.head()

  Postcode      Borough                           Neighbourhood
0      M1B  Scarborough                          Rouge, Malvern
1      M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2      M1E  Scarborough       Guildwood, Morningside, West Hill
3      M1G  Scarborough                                  Woburn
4      M1H  Scarborough                               Cedarbrae

<h4> here I rename "Not assigned" Neighbourhoods with Borough names</h4>

In [9]:
nb_df_combine.loc[nb_df_combine['Neighbourhood']=='Not assigned', ['Neighbourhood']] = nb_df_combine['Borough']
nb_df_combine.head(25)

   Postcode      Borough                                      Neighbourhood
0       M1B  Scarborough                                     Rouge, Malvern
1       M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2       M1E  Scarborough                  Guildwood, Morningside, West Hill
3       M1G  Scarborough                                             Woburn
4       M1H  Scarborough                                          Cedarbrae
5       M1J  Scarborough                                Scarborough Village
6       M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7       M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8       M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9       M1N  Scarborough                        Birch Cliff, Cliffside West
10      M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...
11      M1R  Scarborough                                  Maryvale, Wexford
12      M1S  Scarborough                                          Agincourt
13      M1T  Scarborough            Clarks Corners, Sullivan, Tam O'Shanter
14      M1V  Scarborough  Agincourt North, L'Amoreaux East, Milliken, St...
15      M1W  Scarborough                                    L'Amoreaux West
16      M1X  Scarborough                                        Upper Rouge
17      M2H   North York                                  Hillcrest Village
18      M2J   North York                       Fairview, Henry Farm, Oriole
19      M2K   North York                                    Bayview Village
20      M2L   North York                           Silver Hills, York Mills
21      M2M   North York                            Newtonbrook, Willowdale
22      M2N   North York                                   Willowdale South
23      M2P   North York                                    York Mills West
24      M2R   North York                                    Willowdale West

In [10]:
#Shape of the output for verifiying correct length of Datafrane
nb_df_combine.shape

(103, 3)

<h4> Install geocoder library and use to obtain Long and Lat for postal codes. Adding while loop to be sure values are available</h4>

In [ ]:
import geocoder # import geocoder

for row in nb_df_combine.iterrows():
    postal_code = row[1][0]
    # initialize your variable to None
    lat_lng_coords = None

    # loop until you get the coordinates
    while(lat_lng_coords is None):
      g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
      lat_lng_coords = g.latlng
      print(lat_lng_coords)

    latitude = lat_lng_coords[0]
    longitude = lat_lng_coords[1]
    print(postal_code, latitude, longitude)
    nb_df_combine['Latitude']=latitude
    nb_df_combine['Longitude']=longitude

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None

In [12]:
lat_long = pd.read_csv(r'C:\Users\gtm12\OneDrive\Documents\Python\ibmDS\Capstone\IBM_DS_Capstone\Geospatial_Coordinates.csv')
lat_long.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [18]:
lat_long.rename({"Postal Code":"Postcode"}, axis=1, inplace=True)
lat_long.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [20]:
merged_df = pd.merge(nb_df_combine, lat_long, on="Postcode")
merged_df.head()

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476